### ISSUE TITLE
Json Extra Data Error in get_facts() on live equipent

### ISSUE THREAD

**Issue by haderp** [napalm-automation/napalm-cumulus#10]
get_facts() issue when run on live equipment 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "napalm_cumulus/cumulus.py", line 185, in get_facts
    interfaces = json.loads(self.device.send_command('sudo net show interface all json'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 6653 column 1 - line 6666 column 1 (char 210381 - 210855)

**Comment by GGabriele** [comment]
Can you provide the output from the `sudo net show interface all json` command?

**Comment by haderp** [comment]
@GGabriele 
[sanitized_net_show_interface_jason.zip](https://github.com/napalm-automation/napalm-cumulus/files/766862/sanitized_net_show_interface_jason.zip)
